services:
  hummingbot:
    container_name: hummingbot
    image: hummingbot/hummingbot:latest
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .compose.env
    environment:
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - WS_PROXY=${WS_PROXY:-${HTTP_PROXY:-}}
      - WSS_PROXY=${WSS_PROXY:-${HTTPS_PROXY:-}}
      - ALL_PROXY=${ALL_PROXY:-}
      - NO_PROXY=localhost,127.0.0.1
      - http_proxy=${HTTP_PROXY:-}
      - https_proxy=${HTTPS_PROXY:-}
      - ws_proxy=${WS_PROXY:-${HTTP_PROXY:-}}
      - wss_proxy=${WSS_PROXY:-${HTTPS_PROXY:-}}
      - all_proxy=${ALL_PROXY:-}
      - no_proxy=localhost,127.0.0.1
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./controllers:/home/hummingbot/controllers
      - ./hummingbot/strategy_v2/executors/position_executor/data_types.py:/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/data_types.py:ro
      - ./hummingbot/strategy_v2/executors/position_executor/position_executor.py:/home/hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py:ro
      - ./hummingbot/strategy_v2/controllers/market_making_controller_base.py:/home/hummingbot/hummingbot/strategy_v2/controllers/market_making_controller_base.py
      - ./hummingbot/core/web_assistant/connections/connections_factory.py:/home/hummingbot/hummingbot/core/web_assistant/connections/connections_factory.py
      - ./hummingbot/connector/derivative/okx_perpetual/okx_perpetual_derivative.py:/home/hummingbot/hummingbot/connector/derivative/okx_perpetual/okx_perpetual_derivative.py
      - ./hummingbot/connector/derivative/okx_perpetual/okx_perpetual_user_stream_data_source.py:/home/hummingbot/hummingbot/connector/derivative/okx_perpetual/okx_perpetual_user_stream_data_source.py:ro
      - ./hummingbot/connector/perpetual_derivative_py_base.py:/home/hummingbot/hummingbot/connector/perpetual_derivative_py_base.py:ro
      - ./hummingbot/core/data_type/order_book_tracker.py:/home/hummingbot/hummingbot/core/data_type/order_book_tracker.py:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    init: true
    command:
      - hbot
      - start
      - conf_okx_multi.yml
      - --v2-script
      - --foreground
